server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: sunisland-backend
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/sunisland}
  graphql:
    graphiql:
      enabled: true
    path: /graphql

management:
  endpoints:
    web:
      exposure:
        include: health,info
